FROM php:8.4-fpm-alpine3.21

LABEL maintainer="DaKa"
ENV TZ=America/Bogota
WORKDIR /app

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime  \
    && echo $TZ > /etc/timezone \
    && apk update && apk add   \
    nginx \
    tzdata \
    nano \
    bash \
    curl \
    nano \
    wget \
    supervisor \
    libzip-dev \
    libpng-dev \
    postgresql-dev \
    && docker-php-ext-install pdo pdo_pgsql \
    && docker-php-ext-install zip \
    && docker-php-ext-configure gd \
    && docker-php-ext-install -j$(nproc) gd \
    && php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && mkdir -p /var/log/supervisor

RUN docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd \
    && docker-php-ext-configure mysqli --with-mysqli=mysqlnd \
    && docker-php-ext-install pdo_mysql
# RUN docker-php-ext-configure intl && docker-php-ext-install intl

# COPY . .
COPY ./docker/production.php.ini $PHP_INI_DIR/php.ini
COPY ./docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY ./docker/cron.d /etc/crontabs/root
COPY ./docker/Nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./docker/Nginx/nginx.conf /etc/nginx/nginx.conf
# COPY ./docker/production.env .env

# RUN  composer install --optimize-autoloader --no-dev  \
#     &&  php artisan route:cache  \
#     &&  php artisan storage:link  \
#     && chmod -R ug+rwx storage bootstrap/cache \
#     && chgrp -R www-data storage bootstrap/cache \
#     && chown -R www-data:www-data *

CMD sh -c "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"

